# [Info]
site_name: MariaYe - Jialin Ye's portfolio # 左上角标题
site_url: https://mariaye.github.io
site_author: Jialin Ye
site_description: Jialin Ye's portfolio website

theme:
  name: material
  palette:
    - scheme: default # 日间模式
      primary: indigo # 上方的
      accent: orange # 链接等可交互元件的高亮色
      toggle:
        icon: material/weather-night # 图标
        name: 切换至夜间模式 # 鼠标悬浮提示
    - scheme: slate # 夜间模式
      primary: indigo
      accent: orange
      toggle:
        icon: material/weather-sunny
        name: 切换至日间模式